### ISSUE TITLE
read_trigger gets created in "all" struct only?

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#6]
```
'alarms': {'read': True, 'write': False, 'item_type': 'dict', 'read_cmd': '{CUSTOM_ATTR1} alarms 0 100 all', 'dev_datatype': 'SqueezeAlarms', 'reply_token': 'REGEX', 'reply_pattern': r'{CUSTOM_PATTERN1} alarms 0 100 all fade:\d+ count:\d+ (.*)', 'item_attrs': {'initial': True, 'read_groups': [{'name': 'player.control.alarms', 'trigger': 'query'}]}}
```

When creating the struct, this is correct:
```
ALL:
    player:
        control:
            alarms:
                type: dict
                ..

                query:
                    type: bool
                    enforce_updates: true
                    md_device: DEVICENAME
                    md_read_group_trigger: player.control.alarms.query
```

While the struct called "player" does not have the correct item tree
